domain: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx.nodes.k8s.fr-par.scw.cloud

global:
  storageClassName: scw-bssd # Specific to Scaleway Kapsule
  ## Domain settings
  ## The domain must match the address from where you access the server
  ## It's recommended to configure this value, otherwise certain functionality might not work,
  ## like attachment downloads, email links and U2F.
  ## For U2F to work, the server must use HTTPS, you can use Let's Encrypt for free certs
  DOMAIN: https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx.nodes.k8s.fr-par.scw.cloud

  ## Mail specific settings, set SMTP_HOST and SMTP_FROM to enable the mail service.
  ## To make sure the email links are pointing to the correct host, set the DOMAIN variable.
  ## Note: if SMTP_USERNAME is specified, SMTP_PASSWORD is mandatory
  SMTP_HOST: smtp.domain.tld
  SMTP_FROM: vaultwarden@domain.tld
  SMTP_FROM_NAME: Vaultwarden
  SMTP_SECURITY: starttls # ("starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
  SMTP_PORT: 587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 is outdated and used with Implicit TLS.
  SMTP_TIMEOUT: 15

  ## Controls if new users can register (disable after first user registered)
  SIGNUPS_ALLOWED: true
